/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze */
        get: operations["analyze_api_analyze_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route
         * @description 선택한 시설 하나의 경로 (v2.4 4-3 10단계, 4-4).
         *
         *     없는 `fid`는 **새 오류 코드를 만들지 않고 404**다. 프론트는 body가 아니라 404를
         *     보고 재분석한다. 제품 오류 6종은 평소대로 `{code, message}`로 나간다.
         */
        get: operations["route_api_route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description 카카오 로컬 검색 프록시 (v2.4 4-4).
         *
         *     **검색어를 서버에 저장하거나 캐시하지 않는다**(4-4, 5절). 실패 처리도 4-4대로다 —
         *     카카오 timeout은 기존 `TIMEOUT`(504), 그 밖의 카카오 실패는 계약 밖 HTTP 실패(502).
         *     새 제품 오류 코드를 만들지 않는다.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Computed At
             * Format: date-time
             * @description 실제 분석 계산 시각. UTC aware ISO 8601. 캐시 히트는 원 값을 그대로 돌려준다
             */
            computed_at: string;
            density: components["schemas"]["Density"];
            input: components["schemas"]["InputCoord"];
            /** Nearest */
            nearest: components["schemas"]["NearestItem"][];
            region: components["schemas"]["Region"];
            snapped: components["schemas"]["Snapped"];
            versions: components["schemas"]["Versions"];
            /** Warnings */
            warnings: string[];
        };
        /** Density */
        Density: {
            /** Candidates Checked */
            candidates_checked: number;
            /** Candidates Total */
            candidates_total: number;
            /** Cap */
            cap: number;
            /**
             * Category
             * @constant
             */
            category: "food_cafe";
            /**
             * Count
             * @description 항상 존재한다. complete면 정수, capped면 cap(20), incomplete면 null
             */
            count: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "capped" | "incomplete";
        };
        /** Facility */
        Facility: {
            /** Detour Flag */
            detour_flag: boolean;
            /** Fid */
            fid: number;
            /** Name */
            name: string;
            /** Straight M */
            straight_m: number;
            /** Walk M */
            walk_m: number;
            /** Walk Seconds */
            walk_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Data Version
             * @description 데이터 배포본이 없으면 null
             */
            data_version?: string | null;
            /** Status */
            status: string;
            /** Time Model Version */
            time_model_version: string;
        };
        /** InputCoord */
        InputCoord: {
            /**
             * Lat
             * @description 계산 좌표, 소수 5자리
             */
            lat: number;
            /**
             * Lon
             * @description 계산 좌표, 소수 5자리
             */
            lon: number;
        };
        /** LineString */
        LineString: {
            /** Coordinates */
            coordinates: number[][];
            /**
             * Type
             * @default LineString
             */
            type: string;
        };
        /** NearestItem */
        NearestItem: {
            /** @description 항상 존재한다. none·unreachable·uncertain(B)에서는 null */
            best: components["schemas"]["Facility"] | null;
            /**
             * Category
             * @enum {string}
             */
            category: "convenience" | "grocery" | "pharmacy" | "medical" | "park";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "uncertain" | "unreachable" | "none";
            /**
             * Top3
             * @description 항상 존재한다. null이 될 수 없고 비면 []. best가 있으면 top3[0] == best
             */
            top3: components["schemas"]["Facility"][];
        };
        /** Region */
        Region: {
            /** Label */
            label: string;
            /** Supported */
            supported: boolean;
            /** Verified Area */
            verified_area: boolean;
        };
        /**
         * RouteResponse
         * @description `/api/route` 응답 (v2.4 4-4).
         *
         *     `versions`는 **필수**이며 `AnalyzeResponse.versions`와 같은 모양이다. 프론트는 화면이
         *     들고 있는 분석의 `versions`와 이 값이 다르면 경로를 그리지 않고 재분석한다(4-5).
         *     같은 분석에서 값을 가져오므로 정상 경로에서는 항상 같다.
         *
         *     `snapped_origin`·`snapped_dest`는 분석이 실제로 사용한 스냅 지점이다. 그 지점을
         *     가리키는 OSRM 내부 토큰(hint)은 **응답에 싣지 않는다**(v2.4 4-3 10단계).
         */
        RouteResponse: {
            geometry: components["schemas"]["LineString"];
            snapped_dest: components["schemas"]["Snapped"];
            snapped_origin: components["schemas"]["Snapped"];
            versions: components["schemas"]["Versions"];
            /** Walk M */
            walk_m: number;
            /** Walk Seconds */
            walk_seconds: number;
        };
        /**
         * SearchResult
         * @description `/api/search` 결과 한 건 (v2.4 4-4). 카카오 결과의 축약이며 서버에 저장하지 않는다.
         *
         *     좌표는 카카오가 준 값 그대로다. **여기서 5자리로 깎지 않는다** — v2.4 4-2의 "입력
         *     시점에 한 번만" 반올림은 사용자가 결과를 고르는 순간이고, 그 한 곳은
         *     `web/src/coords.ts`다. 서버가 미리 깎으면 반올림하는 곳이 둘이 된다.
         */
        SearchResult: {
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
        /** Snapped */
        Snapped: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Snap Distance M */
            snap_distance_m: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Versions */
        Versions: {
            /** Data Version */
            data_version: string;
            /** Poi Date */
            poi_date: string;
            /** Time Model Version */
            time_model_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    route_api_route_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
                fid: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
